version: 3.1.0.{build}
environment:
    PROJECT_NAME:  'Cube.Xui'
    PROJECT_BIN:   'bin\%PLATFORM%\%CONFIGURATION%\net45'
    TEST_TOOL:     '..\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe'
    TEST_ARGS:     'test --no-restore --no-build --logger:Appveyor'
    TEST_FILTERS:  '+[Cube*]* -[*]*NativeMethods -[*]*Properties.*'
    TEST_COVERAGE: 'CoverResults.xml'
    TEST_RESULTS:  'TestResults'
clone_folder: 'C:\Cube\%PROJECT_NAME%'
image: Visual Studio 2019
platform: Any CPU
configuration: Release
skip_tags: true
branches:
    only:
        - master
nuget:
    project_feed: true
    disable_publish_on_pr: true
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget restore "%PROJECT_NAME%.sln"
build:
    project: '%PROJECT_NAME%.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:appveyor
      -target:dotnet.exe
      -targetargs:"%TEST_ARGS% %PROJECT_NAME%.sln"
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
after_test:
    - pip install codecov
    - codecov -f "%TEST_COVERAGE%"
    - xcopy /q /Y /I "Tests\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_RESULTS%\"
artifacts:
    - path: '%TEST_RESULTS%'
