version: 1.16.0.{build}
image: Visual Studio 2019 Preview
platform: Any CPU
configuration: Release
environment:
    PROJECT_NAME:   'Cube.Xui'
    PROJECT_BIN:    'bin\%PLATFORM%\%CONFIGURATION%\net45'
    PROJECT_LIB:    '..\packages'
    TEST_TOOL:      '$(PROJECT_LIB)\OpenCover\4.7.922\tools\OpenCover.Console.exe'
    TEST_CORETOOL:  'nunit3-console.exe'
    TEST_FILTERS:   '+[Cube*]* -[*]*NativeMethods -[*]*Properties.*'
    TEST_RESULT:    'TestResult.xml'
    TEST_COVERAGE:  'CoverResults.xml'
    TEST_LOG:       'TestResults'
branches:
    only:
        - master
skip_tags: true
nuget:
    project_feed: true
    disable_publish_on_pr: true
clone_folder: 'C:\Cube\%PROJECT_NAME%'
before_build:
    - nuget restore "%PROJECT_NAME%.sln"
build:
    project: '%PROJECT_NAME%.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Tests.dll"
      -targetdir:"Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
after_test:
    - xcopy /q /Y /I "Tests\%PROJECT_BIN%\*.log" "%TEST_LOG%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_LOG%\"
artifacts:
    - path: '%TEST_LOG%'
